
package Interfaces_Almacenero;

import Clases.BotonesTablaCompras;
import Clases.ItemCombo;
import Clases.TablaCompras;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import Conexion.Conexion;
import DAO.CompraDAO;
import Modelos.Compra;
import java.sql.Connection; 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;



public class Compras extends javax.swing.JInternalFrame {
    
    // 1. Variable para guardar el ID del usuario que está comprando
    private int idUsuarioSesion;

    // 2. Modificar el Constructor para pedir el ID
    // Borra 'public Compras() {' y pon este:
    public Compras(int idUsuario) {
        initComponents(); // Esto inicializa los componentes visuales
        
        this.idUsuarioSesion = idUsuario; // Guardamos el ID que nos manda el menú
        
        // (Opcional) Prueba en consola
        System.out.println("Formulario Compras abierto por usuario ID: " + idUsuario);
    }
    
    
    
    
    
    private static Compras instancia;
// Variables de estado en la clase Compras
    private int idCompraSeleccionada = -1;
    private int filaEnEdicion = -1;
    private boolean modoEdicion = false;


    // crea un objeto de BotonesTablaCompras 
BotonesTablaCompras manejadorBotones;
    
    //creamos un avariable para el modelo la tabla
    TablaCompras c_tabla = new TablaCompras();
   // Reemplaza la declaración anterior con esta:
private JComboBox<ItemCombo> cbxProductoReal;


   public Compras() {
    initComponents(
    );

    // Cargar datos en la tabla
    c_tabla.cargarDatos(tblCompras);
    configurarTabla();
 cargarProductosEnCombo(cbxProducto); // aquí llenas el combo con la BD


    // Renderizador para mostrar botones en las celdas
    tblCompras.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus,
                int row, int column) {

            if (value instanceof JButton) {
                return (JButton) value;
            }
            return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        }
    });

    // Instancia el manejador pasando la tabla y los campos del formulario
    manejadorBotones = new BotonesTablaCompras(
        tblCompras,
        txtCantidad,
        txtPrecio,
        txtHumedad,
        txtRendimiento,
        txtGuia,
        txtSocio
    );

    // Agrega el listener de clics a la tabla
    tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            manejadorBotones.manejarEventoTabla(evt);
        }
    });

    setBorder(null);
    BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
    ui.setNorthPane(null);

    try {
        setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
}

    
  

  
   
    
public static Compras getInstancia(){
     if(instancia == null || instancia.isClosed()){
     instancia = new Compras();
     }
     return instancia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtGuia = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtHumedad = new javax.swing.JTextField();
        txtRendimiento = new javax.swing.JTextField();
        cbxProducto = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        txtDniSocio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSocio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Productos");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Rendimiento");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("DNI Socio");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Humedad");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Precio");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Guia de ingreso");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        txtHumedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHumedadActionPerformed(evt);
            }
        });

        cbxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CO", "C", "O" }));
        cbxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductoActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtDniSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniSocioActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Socio");

        txtSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGuia)
                            .addComponent(txtDniSocio)
                            .addComponent(txtSocio)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHumedad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHumedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(txtRendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDniSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompras);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHumedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHumedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHumedadActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
btnRegistrar.addActionListener(e -> {
    try {
        // 1. Obtener datos de la interfaz
        String producto = String.valueOf(cbxProducto.getSelectedItem());
        int idProducto = obtenerIdProducto(producto); // Método que ya tienes

        double cantidadVal = Double.parseDouble(txtCantidad.getText());
        double humedadVal = Double.parseDouble(txtHumedad.getText());
        double precioVal = Double.parseDouble(txtPrecio.getText());
        double rendimientoVal = Double.parseDouble(txtRendimiento.getText());      
        String guia = txtGuia.getText();
        String socio = txtSocio.getText(); 
        
        // Fecha actual
        String fecha = java.time.LocalDateTime.now()
            .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        // Validaciones básicas
        if (guia.isEmpty() || txtCantidad.getText().isEmpty() || txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos obligatorios");
            return;
        }

        // 2. Conectar y Guardar
        try (Connection con = Conexion.getConexion()) {
            
            // OJO: Aquí obtenemos el ID del socio (debes tener este método o usar un combo)
            // Por ahora uso 1 para probar, pero deberías usar: obtenerIdSocio(socio);
            int idSocio = 1; 

            String sql = "INSERT INTO compra (id_usuario, id_producto, cantidad, humedad, precio, rendimiento, guia_ingreso, id_socio, fecha_registro) " +
                         "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            try (PreparedStatement ps = con.prepareStatement(sql)) {

                // --- AQUÍ ESTABA EL ERROR DE ORDEN ---
                
                // 1. id_usuario: Usamos la variable que pasamos desde el Login
                ps.setInt(1, this.idUsuarioSesion); 

                // 2. id_producto
                ps.setInt(2, idProducto);

                // 3. cantidad
                ps.setDouble(3, cantidadVal);

                // 4. humedad
                ps.setDouble(4, humedadVal);
 
                // 5. precio
                ps.setDouble(5, precioVal);

                // 6. rendimiento
                ps.setDouble(6, rendimientoVal);

                // 7. guia_ingreso
                ps.setString(7, guia);

                // 8. id_socio
                ps.setInt(8, idSocio);

                // 9. fecha_registro
                ps.setString(9, fecha);

                // Ejecutar
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Compra registrada correctamente.");
            }
        }

        // 3. Actualizar la tabla visualmente
        new TablaCompras().cargarDatos(tblCompras);

        // 4. Limpiar campos
        txtCantidad.setText("");
        txtPrecio.setText("");
        txtHumedad.setText("");
        txtRendimiento.setText("");
        txtGuia.setText("");
        txtSocio.setText("");

    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(null, "Error: Ingrese números válidos en cantidad/precio/etc.");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al registrar: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseClicked
    int fila = tblCompras.rowAtPoint(evt.getPoint());
    int columna = tblCompras.columnAtPoint(evt.getPoint());
    if (fila < 0 || columna < 0) return;

    Object valor = tblCompras.getValueAt(fila, columna);
    if (!(valor instanceof JButton)) return;

    JButton boton = (JButton) valor;
    String nombre = boton.getName();

    // Obtén el ID con seguridad de tipos
    Object idObj = tblCompras.getValueAt(fila, 0);
    int idCompra;
    if (idObj instanceof Integer) {
        idCompra = (Integer) idObj;
    } else {
        try { idCompra = Integer.parseInt(String.valueOf(idObj)); }
        catch (NumberFormatException e) { 
            JOptionPane.showMessageDialog(null, "ID de compra inválido."); 
            return; 
        }
    }

    switch (nombre) {
        case "b_pdf":
            generarPDFDesdeTabla(fila);
            break;

        case "b_eliminar":
            eliminarCompra(idCompra);
            break;

        case "b_modificar":
            cargarDatosEnFormulario(fila); // carga los datos al formulario

            btnRegistrar.setText("Actualizar");
            btnRegistrar.setEnabled(true); // asegúrate de que esté activo
            modoEdicion = true;
            idCompraSeleccionada = idCompra;
            filaEnEdicion = fila;
            break;


    }
    }//GEN-LAST:event_tblComprasMouseClicked
    
    private void txtDniSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniSocioActionPerformed

    private void txtSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocioActionPerformed

    private void cbxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductoActionPerformed

    }//GEN-LAST:event_cbxProductoActionPerformed

private void generarPDFDesdeTabla(int fila) {
    TablaCompras tabla = new TablaCompras();
    tabla.generarPDF_Fila(tblCompras, fila);
}

private void eliminarCompra(int idCompra) {
    try (Connection con = Conexion.getConexion();
     PreparedStatement ps = con.prepareStatement("DELETE FROM compra WHERE id=?")) {

    ps.setInt(1, idCompra);
    ps.executeUpdate();
    JOptionPane.showMessageDialog(null, "Compra eliminada.");
    new TablaCompras().cargarDatos(tblCompras);

} catch (Exception e) {
    e.printStackTrace();
}

}

private void cargarDatosEnFormulario(int fila) {
    txtCantidad.setText(tblCompras.getValueAt(fila, 2).toString());
    txtPrecio.setText(tblCompras.getValueAt(fila, 3).toString());
    txtHumedad.setText(tblCompras.getValueAt(fila, 4).toString());
    txtRendimiento.setText(tblCompras.getValueAt(fila, 5).toString());
    txtGuia.setText(tblCompras.getValueAt(fila, 6).toString());
    txtSocio.setText(tblCompras.getValueAt(fila, 7).toString());

    // Guarda el ID para la actualización
    Object idObj = tblCompras.getValueAt(fila, 0);
    idCompraSeleccionada = Integer.parseInt(String.valueOf(idObj));

    // Cambia el botón principal
    btnRegistrar.setText("Actualizar");
    btnRegistrar.setEnabled(true);
    modoEdicion = true;
    filaEnEdicion = fila;
}


private boolean guardarCambiosEnBD(int fila, int columna) {
    try (Connection con = Conexion.getConexion();
         PreparedStatement ps = con.prepareStatement(
                 "UPDATE compra SET cantidad=?, precio=?, humedad=?, rendimiento=?, guia_ingreso=? WHERE id=?")) {

        ps.setDouble(1, Double.parseDouble(txtCantidad.getText()));
        ps.setDouble(2, Double.parseDouble(txtPrecio.getText()));
        ps.setDouble(3, Double.parseDouble(txtHumedad.getText()));
        ps.setDouble(4, Double.parseDouble(txtRendimiento.getText()));
        ps.setString(5, txtGuia.getText());
        ps.setInt(6, idCompraSeleccionada);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Compra actualizada correctamente.");
        return true;

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al actualizar la compra: " + e.getMessage());
        return false;
    }
}

private void configurarTabla() {
    DefaultTableModel modelo = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Producto", "Cantidad", "Precio", "Humedad", "Rendimiento",
            "Guía de remisión", "Socio", "Fecha", "PDF", "Eliminar", "Modificar"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column >= 9  ; // solo botones son editables
        }
    };

    tblCompras.setModel(modelo);
    tblCompras.setRowHeight(30);

    // Ocultar columna ID (columna 0)
    if (tblCompras.getColumnModel().getColumnCount() > 0) {
        tblCompras.getColumnModel().getColumn(0).setMinWidth(0);
        tblCompras.getColumnModel().getColumn(0).setMaxWidth(0);
        tblCompras.getColumnModel().getColumn(0).setWidth(0);
    }
}

private void cargarProductosEnCombo(JComboBox<String> combo) {
    try (Connection con = Conexion.getConexion();
         PreparedStatement ps = con.prepareStatement("SELECT nombre FROM producto");
         ResultSet rs = ps.executeQuery()) {

        combo.removeAllItems();

        while (rs.next()) {
            combo.addItem(rs.getString("nombre")); // solo el nombre
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar productos: " + e.getMessage());
    }
}

private int obtenerIdProducto(String nombreProducto) {
    try (Connection con = Conexion.getConexion();
         PreparedStatement ps = con.prepareStatement("SELECT id FROM producto WHERE nombre = ?")) {
        ps.setString(1, nombreProducto);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt("id");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return -1; // si no se encuentra
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblCompras;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDniSocio;
    private javax.swing.JTextField txtGuia;
    private javax.swing.JTextField txtHumedad;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRendimiento;
    private javax.swing.JTextField txtSocio;
    // End of variables declaration//GEN-END:variables

    
   
    

}
