/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces_Almacenero;

import Clases.TablaCompras;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jheff
 */
public class Lista_Compras extends javax.swing.JInternalFrame {

         private static Lista_Compras instancia;
         
         
    //creamos un avariable para el modelo la tabla
    TablaCompras v_tabla = new TablaCompras();
    //Declara una variable para guardar la fila activa,,,limpia con un control de estado.
    private int filaEnEdicion = -1;

    /**
     * Creates new form Lista_Compras
     */
    public Lista_Compras() {
        
        initComponents();
        
        
       
        
         //llamos al mtodo llamar tabla y ponemos el nombre de la tabla
        v_tabla.ver_tabla(tblListaCompras);
        
        
        
         // Quitar bordes y título
        setBorder(null);
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        // Abrir maximizado
        try {
            setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
        
    }
    
    public static Lista_Compras getInstancia(){
     if(instancia == null || instancia.isClosed()){
     instancia = new Lista_Compras();
     }
     return instancia;
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtSocioBuscar = new javax.swing.JTextField();
        txtGuiaRemisionBuscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnDescargarTodo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCompras = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Buscar Por Socio");

        jLabel3.setText("Guia de Remision");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnDescargarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf_2.png"))); // NOI18N
        btnDescargarTodo.setText("Descargar todo");
        btnDescargarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSocioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtGuiaRemisionBuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnDescargarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuiaRemisionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSocioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196)
                .addComponent(btnDescargarTodo)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblListaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListaCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaCompras);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblListaComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaComprasMouseClicked
 int fila = tblListaCompras.rowAtPoint(evt.getPoint());
    int columna = tblListaCompras.columnAtPoint(evt.getPoint());

    if (fila >= 0 && columna >= 0) {
        Object value = tblListaCompras.getValueAt(fila, columna);

        if (value instanceof JButton) {
            JButton boton = (JButton) value;
            String nombre = boton.getName();

            // === BOTÓN PDF ===
            if (nombre.equals("b_pdf")) {
                generarPDF_Fila_ListaCompras(fila); // <-- Genera solo la fila
            }

            // === BOTÓN ELIMINAR ===
            if (nombre.equals("b_eliminar")) {
                System.out.println("Click en el botón Eliminar");
                ((DefaultTableModel) tblListaCompras.getModel()).removeRow(fila);
            }

        // === BOTÓN MODIFICAR ===
            if (nombre.equals("b_modificar")) {
                System.out.println("Click en el botón Modificar");

                // Si hay otra fila en edición, la restauramos
                if (filaEnEdicion != -1 && filaEnEdicion != fila) {
                    JButton btnModificarAntiguo = new JButton("Modificar");
                    btnModificarAntiguo.setName("b_modificar");
                    tblListaCompras.setValueAt(btnModificarAntiguo, filaEnEdicion, columna);
                }

                // Activamos el modo Guardar solo para la fila actual
                JButton btnGuardar = new JButton("Guardar");
                btnGuardar.setName("b_guardar");
                tblListaCompras.setValueAt(btnGuardar, fila, columna);
                tblListaCompras.repaint();

                filaEnEdicion = fila; // guardamos la fila que se está editando
            }

            // === BOTÓN GUARDAR ===
            if (nombre.equals("b_guardar")) {
                System.out.println("Click en el botón Guardar");

                String producto = tblListaCompras.getValueAt(fila, 0).toString();
                String cantidad = tblListaCompras.getValueAt(fila, 1).toString();
                String precio = tblListaCompras.getValueAt(fila, 2).toString();

                System.out.println("Guardando cambios");

                // Restauramos el botón a "Modificar"
                JButton btnModificar = new JButton("Modificar");
                btnModificar.setName("b_modificar");
                tblListaCompras.setValueAt(btnModificar, fila, columna);
                tblListaCompras.repaint();

                filaEnEdicion = -1; // limpiamos la fila activa
            }
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tblListaComprasMouseClicked

    private void btnDescargarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarTodoActionPerformed
try {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar reporte de compras");
    FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
    fileChooser.setFileFilter(filtro);

    int seleccion = fileChooser.showSaveDialog(this);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivoSeleccionado = fileChooser.getSelectedFile();
        String ruta = archivoSeleccionado.getAbsolutePath();
        if (!ruta.toLowerCase().endsWith(".pdf")) {
            ruta += ".pdf";
        }

        Document documento = new Document();
        PdfWriter.getInstance(documento, new FileOutputStream(ruta));
        documento.open();

        com.itextpdf.text.Font fuentePequena = FontFactory.getFont(FontFactory.HELVETICA, 8);
        com.itextpdf.text.Font fuenteEncabezado = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);

        documento.add(new Paragraph("REPORTE COMPLETO DE COMPRAS\n\n", fuenteEncabezado));
        documento.add(new Paragraph("Generado el: " + 
            new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()) + "\n\n", fuentePequena));

        // --- LÓGICA DE TABLA ---
        int columnas = tblListaCompras.getColumnCount();
        List<Integer> columnasValidas = new ArrayList<>();
        for (int c = 0; c < columnas; c++) {
            String nombre = tblListaCompras.getColumnName(c);
            if (!nombre.equalsIgnoreCase("PDF") &&
                !nombre.equalsIgnoreCase("ELIMINAR") &&
                !nombre.equalsIgnoreCase("MODIFICAR")) {
                columnasValidas.add(c);
            }
        }

        PdfPTable tablaPDF = new PdfPTable(columnasValidas.size());
        tablaPDF.setWidthPercentage(100);
        tablaPDF.setSpacingBefore(10f);
        tablaPDF.setSpacingAfter(10f);

        // Encabezados
        for (int c : columnasValidas) {
            PdfPCell encabezado = new PdfPCell(new Phrase(tblListaCompras.getColumnName(c), fuenteEncabezado));
            encabezado.setBackgroundColor(BaseColor.LIGHT_GRAY);
            encabezado.setHorizontalAlignment(Element.ALIGN_CENTER);
            tablaPDF.addCell(encabezado);
        }

        // Todas las filas
        int filas = tblListaCompras.getRowCount();
        for (int f = 0; f < filas; f++) {
            for (int c : columnasValidas) {
                Object valor = tblListaCompras.getValueAt(f, c);
                String texto = (valor instanceof JButton) ? ((JButton) valor).getText() : (valor != null ? valor.toString() : "");
                PdfPCell celda = new PdfPCell(new Phrase(texto, fuentePequena));
                celda.setHorizontalAlignment(Element.ALIGN_CENTER);
                tablaPDF.addCell(celda);
            }
        }

        documento.add(tablaPDF);
        documento.close();

        JOptionPane.showMessageDialog(this, "PDF generado correctamente en:\n" + ruta);
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
    e.printStackTrace();
}

    }//GEN-LAST:event_btnDescargarTodoActionPerformed

    
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarTodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaCompras;
    private javax.swing.JTextField txtGuiaRemisionBuscar;
    private javax.swing.JTextField txtSocioBuscar;
    // End of variables declaration//GEN-END:variables



    
    
    public void generarPDF_Fila_ListaCompras(int fila) {
    Document documento = new Document();
    try {
        if (fila < 0 || fila >= tblListaCompras.getRowCount()) {
            JOptionPane.showMessageDialog(null, "La fila seleccionada no es válida.");
            return;
        }

        // Cuadro de diálogo para elegir ruta
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte de compra");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
        fileChooser.setFileFilter(filtro);

        int seleccion = fileChooser.showSaveDialog(null);
        if (seleccion != JFileChooser.APPROVE_OPTION) {
            return; // Cancelado
        }

        File archivoSeleccionado = fileChooser.getSelectedFile();
        String ruta = archivoSeleccionado.getAbsolutePath();
        if (!ruta.toLowerCase().endsWith(".pdf")) {
            ruta += ".pdf";
        }

        PdfWriter.getInstance(documento, new FileOutputStream(ruta));
        documento.open();

        // Fuentes
        com.itextpdf.text.Font fuenteTitulo = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.BLACK);
        com.itextpdf.text.Font fuenteSubtitulo = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.LIGHT_GRAY);
        com.itextpdf.text.Font fuenteEncabezado = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9);
        com.itextpdf.text.Font fuentePequena = FontFactory.getFont(FontFactory.HELVETICA, 8);

        String fechaHora = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());

        // Título
        Paragraph titulo = new Paragraph("REPORTE DE COMPRA (LISTA)\n", fuenteTitulo);
        titulo.setAlignment(Element.ALIGN_CENTER);
        documento.add(titulo);

        // Subtítulo
        Paragraph subtitulo = new Paragraph("Generado el: " + fechaHora + "\n\n", fuenteSubtitulo);
        subtitulo.setAlignment(Element.ALIGN_RIGHT);
        documento.add(subtitulo);

        documento.add(new Paragraph("Datos de la fila seleccionada:\n\n", fuentePequena));

        // Columnas válidas
        int columnas = tblListaCompras.getColumnCount();
        List<Integer> columnasValidas = new ArrayList<>();
        for (int c = 0; c < columnas; c++) {
            String nombre = tblListaCompras.getColumnName(c);
            if (!nombre.equalsIgnoreCase("PDF") &&
                !nombre.equalsIgnoreCase("ELIMINAR") &&
                !nombre.equalsIgnoreCase("MODIFICAR")) {
                columnasValidas.add(c);
            }
        }

        // Tabla PDF
        PdfPTable tablaPDF = new PdfPTable(columnasValidas.size());
        tablaPDF.setWidthPercentage(100);
        tablaPDF.setSpacingBefore(15f);
        tablaPDF.setSpacingAfter(15f);

        // Encabezados
        for (int c : columnasValidas) {
            PdfPCell encabezado = new PdfPCell(new Phrase(tblListaCompras.getColumnName(c), fuenteEncabezado));
            encabezado.setBackgroundColor(new BaseColor(102,153,0)); ///////////////////////////color 
            encabezado.setHorizontalAlignment(Element.ALIGN_CENTER);
            encabezado.setBorderWidth(1f);
            tablaPDF.addCell(encabezado);
        }

        // Datos de la fila
        for (int c : columnasValidas) {
            Object valor = tblListaCompras.getValueAt(fila, c);
            String texto = (valor instanceof JButton) ? ((JButton) valor).getText() : (valor != null ? valor.toString() : "");
            PdfPCell celda = new PdfPCell(new Phrase(texto, fuentePequena));
            celda.setHorizontalAlignment(Element.ALIGN_CENTER);
            celda.setBorderWidth(0.5f);
            tablaPDF.addCell(celda);
        }

        documento.add(tablaPDF);

        // Pie de página
        Paragraph pie = new Paragraph("Cooperativa Agraria Cafetalera Bagua Grande", 
            FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8, BaseColor.GRAY));
        pie.setAlignment(Element.ALIGN_CENTER);
        documento.add(pie);

        JOptionPane.showMessageDialog(null, "PDF generado correctamente:\n" + ruta);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al generar PDF: " + e.getMessage());
        e.printStackTrace();
    } finally {
        if (documento.isOpen()) {
            documento.close();
        }
    }
}







}
