/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces_Almacenero;

import Conexion.Conexion;
import Entidades.ITProducto;
import Interfaces_Almacenero.RealizarSalida;
import java.awt.Desktop;
import java.io.File;
import java.io.PrintWriter;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class ListarSalidas extends javax.swing.JInternalFrame {
private static ListarSalidas instancia;

    public ListarSalidas() {
        initComponents();
        configurarVentana();
        cargarProductosFiltro();     // Llena el ComboBox de productos
        cargarTodasLasSalidas();     // Carga inicial
        configurarTabla();
        configurarEventos();
    }

    public static ListarSalidas getInstancia() {
        if (instancia == null || instancia.isClosed()) {
            instancia = new ListarSalidas();
        }
        return instancia;
    }
    
    private void configurarVentana() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }
    
    private void configurarTabla() {
        tblSalidas.getColumnModel().getColumn(0).setMinWidth(0);
        tblSalidas.getColumnModel().getColumn(0).setMaxWidth(0);
        tblSalidas.getColumnModel().getColumn(0).setWidth(0);
    }
    private void configurarEventos() {
        // Habilitar/deshabilitar botones según selección
        tblSalidas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                boolean seleccionado = tblSalidas.getSelectedRow() != -1;
                btnModificar.setEnabled(seleccionado);
                btnEliminar.setEnabled(seleccionado);
                btnDescargar.setEnabled(tblSalidas.getRowCount() > 0);
            }
        });
    }
    // CARGAR TODAS LAS SALIDAS
    private void cargarTodasLasSalidas() {
        cargarSalidas("", "");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalidas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarOrden = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnDescargar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cbxFiltroProducto = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSalidas);

        jLabel1.setText("Buscar por numero de orden ");

        jLabel2.setText("Filtrar por producto");

        btnFiltrar.setText("q");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("q");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnDescargar.setText("Descargar");
        btnDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarOrden, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDescargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addComponent(cbxFiltroProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrar)
                    .addComponent(cbxFiltroProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addComponent(btnDescargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
int fila = tblSalidas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una salida para eliminar");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "¿Eliminar esta salida permanentemente?", "Confirmar",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            
            int id = (int) tblSalidas.getValueAt(fila, 0);
            try (Connection cn = Conexion.getConexion();
                 PreparedStatement pst = cn.prepareStatement("DELETE FROM salida WHERE id = ?")) {
                pst.setInt(1, id);
                pst.executeUpdate();
                cargarTodasLasSalidas();
                JOptionPane.showMessageDialog(this, "Salida eliminada");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String orden = txtBuscarOrden.getText().trim();
        String filtroOrden = orden.isEmpty() ? "" : "AND s.numero_orden LIKE '%" + orden + "%'";
        
        ITProducto item = (ITProducto) cbxFiltroProducto.getSelectedItem();
        String filtroProd = (item == null || item.getId() == 0) ? "" : "AND s.id_producto = " + item.getId();
        
        cargarSalidas(filtroOrden, filtroProd);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
     ITProducto item = (ITProducto) cbxFiltroProducto.getSelectedItem();
        String filtroProd = (item == null || item.getId() == 0) ? "" : "AND s.id_producto = " + item.getId();
        
        String orden = txtBuscarOrden.getText().trim();
        String filtroOrden = orden.isEmpty() ? "" : "AND s.numero_orden LIKE '%" + orden + "%'";
        
        cargarSalidas(filtroOrden, filtroProd); // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarActionPerformed
exportarTablaActualACSV();        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescargarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
int fila = tblSalidas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una salida para modificar");
            return;
        }
        int idSalida = (int) tblSalidas.getValueAt(fila, 0);

        JDesktopPane desktop = getDesktopPane();
        RealizarSalida form = RealizarSalida.getInstancia();
        form.cargarSalidaParaEditar(idSalida);

        if (!desktop.isAncestorOf(form)) {
            desktop.add(form);
        }
        form.setVisible(true);
        form.toFront();        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDescargar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<Entidades.ITProducto> cbxFiltroProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalidas;
    private javax.swing.JTextField txtBuscarOrden;
    // End of variables declaration//GEN-END:variables
// CARGAR CON FILTROS
    private void cargarSalidas(String filtroOrden, String filtroProducto) {
        String sql = "SELECT s.id, s.fecha_salida, p.nombre AS producto, s.cantidad_salida, " +
                     "s.numero_orden, s.destino, s.observaciones, u.usuario " +
                     "FROM salida s " +
                     "JOIN producto p ON s.id_producto = p.id " +
                     "JOIN usuarios u ON s.id_usuario = u.id " +
                     "WHERE 1=1 " +
                     filtroOrden +
                     filtroProducto +
                     " ORDER BY s.fecha_salida DESC";

        String[] titulos = {"ID", "Fecha", "Producto", "Cantidad", "N° Orden", "Destino", "Observaciones", "Usuario"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tblSalidas.setModel(modelo);

        try (Connection cn = Conexion.getConexion();
             PreparedStatement pst = cn.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id"),
                    new SimpleDateFormat("dd/MM/yyyy HH:mm").format(rs.getTimestamp("fecha_salida")),
                    rs.getString("producto"),
                    rs.getDouble("cantidad_salida"),
                    rs.getString("numero_orden"),
                    rs.getString("destino"),
                    rs.getString("observaciones"),
                    rs.getString("usuario")
                };
                modelo.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar salidas: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    // LLENAR COMBO DE PRODUCTOS PARA FILTRO
    private void cargarProductosFiltro() {
        cbxFiltroProducto.addItem(new ITProducto(0, "Todos los productos"));
        try (Connection cn = Conexion.getConexion();
             PreparedStatement pst = cn.prepareStatement("SELECT id, nombre FROM producto ORDER BY nombre")) {
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                cbxFiltroProducto.addItem(new ITProducto(rs.getInt("id"), rs.getString("nombre")));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    

// MÉTODO PARA EXPORTAR LA TABLA ACTUAL A CSV
private void exportarTablaActualACSV() {
    if (tblSalidas.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No hay datos para exportar", 
                                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Selector de archivo
    JFileChooser selector = new JFileChooser();
    selector.setDialogTitle("Guardar lista de salidas como CSV");

    String fechaHora = new SimpleDateFormat("dd-MM-yyyy_HHmm").format(new java.util.Date());
    String nombreSugerido = "Lista_Salidas_" + fechaHora + ".csv";
    selector.setSelectedFile(new File(nombreSugerido));

    FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo CSV (*.csv)", "csv");
    selector.setFileFilter(filtro);

    int opcion = selector.showSaveDialog(this);
    if (opcion != JFileChooser.APPROVE_OPTION) {
        return; // Canceló
    }

    File archivo = selector.getSelectedFile();
    if (!archivo.getName().toLowerCase().endsWith(".csv")) {
        archivo = new File(archivo.getAbsolutePath() + ".csv");
    }

    // Confirmar sobrescritura
    if (archivo.exists()) {
        int confirmar = JOptionPane.showConfirmDialog(this,
            "El archivo ya existe. ¿Reemplazar?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar != JOptionPane.YES_OPTION) {
            return;
        }
    }

    // EXPORTAR DATOS DE LA TABLA
    try (PrintWriter pw = new PrintWriter(archivo, "UTF-8")) {
        // ENCABEZADOS (sin la columna ID oculta)
        for (int col = 1; col < tblSalidas.getColumnCount(); col++) {
            pw.print(tblSalidas.getColumnName(col));
            if (col < tblSalidas.getColumnCount() - 1) pw.print(",");
        }
        pw.println();

        // FILAS VISIBLES
        for (int row = 0; row < tblSalidas.getRowCount(); row++) {
            for (int col = 1; col < tblSalidas.getColumnCount(); col++) { // Salta ID
                Object valor = tblSalidas.getValueAt(row, col);
                String texto = (valor != null) ? valor.toString() : "";
                // Escapar comas y comillas para CSV correcto
                if (texto.contains(",") || texto.contains("\"") || texto.contains("\n")) {
                    texto = "\"" + texto.replace("\"", "\"\"") + "\"";
                }
                pw.print(texto);
                if (col < tblSalidas.getColumnCount() - 1) pw.print(",");
            }
            pw.println();
        }

        JOptionPane.showMessageDialog(this,
            "¡Lista de salidas exportada correctamente!\n" + archivo.getAbsolutePath(),
            "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Abrir automáticamente
        Desktop.getDesktop().open(archivo);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error al exportar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    
    

}






