/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces_Almacenero;

import Conexion.Conexion;
import java.awt.Desktop;
import java.io.File;
import java.io.PrintWriter;
import java.sql.*;
import javax.swing.*;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author jheff
 */
public class ListarCompras extends javax.swing.JInternalFrame {
// ← Instancia única
    private static ListarCompras instanciaListar = null;
    /**
     * Creates new form ListarCompras
     */
    private ListarCompras() {
        initComponents();
btnModificar.setIcon(null);
btnEliminar.setIcon(null);
btnExportarExcel.setIcon(null);
// etc.
        cargarTodasLasCompras();
        configurarTabla();


        // Quitar bordes y barra de título
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }
    
    
// MÉTODO SINGLETON CORRECTO
    public static ListarCompras getInstancia() {
        if (instanciaListar == null || instanciaListar.isClosed()) {
            instanciaListar = new ListarCompras();
        }
        return instanciaListar;
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarGuia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnExportarExcel = new javax.swing.JButton();
        btnModificar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        btnBuscarGuia = new javax.swing.JButton();
        txtBuscarDni = new javax.swing.JTextField();
        btnFiltrarDni = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Filtrar por Dni Socio");

        jLabel2.setText("Buscar por numero de guia");

        btnExportarExcel.setText("Descargar");
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarExcelActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscarGuia.setText("q");
        btnBuscarGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGuiaActionPerformed(evt);
            }
        });

        btnFiltrarDni.setText("q");
        btnFiltrarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportarExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltrarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarGuia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrarDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnExportarExcel))
                .addGap(55, 55, 55))
        );

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompras);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGuiaActionPerformed
     String guia = txtBuscarGuia.getText().trim();
        if (guia.isEmpty()) {
            cargarTodasLasCompras();
        } else {
            cargarCompras("WHERE c.guia_ingreso LIKE '%" + guia + "%'");
        }
    }//GEN-LAST:event_btnBuscarGuiaActionPerformed

    private void btnFiltrarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarDniActionPerformed
String dni = txtBuscarDni.getText().trim();
        if (dni.isEmpty()) {
            cargarTodasLasCompras();
        } else {
            cargarCompras("WHERE s.nro_documento LIKE '%" + dni + "%'");
        }
    }//GEN-LAST:event_btnFiltrarDniActionPerformed

    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarExcelActionPerformed
         exportarTablaActualACSV();      // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarExcelActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    
    int fila = tblCompras.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una compra para modificar");
        return;
    }

    int idCompra = (int) tblCompras.getValueAt(fila, 0);

    // OBTENER EL JDesktopPane DEL MENÚ PRINCIPAL
    JDesktopPane desktop = getDesktopPane(); // ← ESTO ES CLAVE

    RealizarCompras form = RealizarCompras.getInstancia();
    form.cargarCompraParaEditar(idCompra);

    // SI NO ESTÁ EN EL DESKTOP, AGREGARLA
    if (!desktop.isAncestorOf(form)) {
        desktop.add(form);
    }

    try {
        form.setMaximum(true);     // Maximizar (opcional)
    } catch (Exception e) {}

    form.setVisible(true);
    form.toFront();
    form.requestFocus();
    // OPCIONAL: cerrar ListarCompras
    // this.dispose();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
// Usa el mismo método que ya tienes en RealizarCompras o reutilízalo aquí
        int fila = tblCompras.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una compra para eliminar");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "¿Eliminar esta compra permanentemente?", "Confirmar",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int id = (int) tblCompras.getValueAt(fila, 0);
            try (Connection cn = Conexion.getConexion();
                 PreparedStatement pst = cn.prepareStatement("DELETE FROM compra WHERE id = ?")) {
                pst.setInt(1, id);
                pst.executeUpdate();
                cargarTodasLasCompras();
                JOptionPane.showMessageDialog(this, "Compra eliminada");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarGuia;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnFiltrarDni;
    private javax.swing.JToggleButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTextField txtBuscarDni;
    private javax.swing.JTextField txtBuscarGuia;
    // End of variables declaration//GEN-END:variables

private void cargarCompras(String condicion) {
        String sql = "SELECT c.id, c.guia_ingreso, c.fecha_registro, s.nombre AS socio, s.nro_documento AS dni, " +
                     "p.nombre AS producto, c.cantidad, c.rendimiento, c.humedad, c.precio, c.precio_total " +
                     "FROM compra c " +
                     "JOIN socio s ON c.id_socio = s.id " +
                     "JOIN producto p ON c.id_producto = p.id " +
                     condicion +
                     " ORDER BY c.fecha_registro DESC";

        String[] titulos = {"ID", "Guía", "Fecha", "Socio", "DNI", "Producto", "Cant.", "Rend.", "Hum.", "Precio", "Total"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tblCompras.setModel(modelo);

        try (Connection cn = Conexion.getConexion();
             PreparedStatement pst = cn.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id"),
                    rs.getString("guia_ingreso"),
                    new SimpleDateFormat("dd/MM/yyyy HH:mm").format(rs.getTimestamp("fecha_registro")),
                    rs.getString("socio"),
                    rs.getString("dni"),
                    rs.getString("producto"),
                    rs.getDouble("cantidad"),
                    rs.getDouble("rendimiento"),
                    rs.getDouble("humedad"),
                    rs.getDouble("precio"),
                    rs.getDouble("precio_total")
                };
                modelo.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
            e.printStackTrace();
        }
    }


private void configurarTabla() {
        // Ocultar columna ID (índice 0)
        tblCompras.getColumnModel().getColumn(0).setWidth(0);
        tblCompras.getColumnModel().getColumn(0).setMinWidth(0);
        tblCompras.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    private void cargarTodasLasCompras() {
        cargarCompras(""); // sin filtro
    }


// LIMPIAR FILTROS
    private void limpiarFiltros() {
        txtBuscarGuia.setText("");
        txtBuscarDni.setText("");
        cargarTodasLasCompras();
    }





private void exportarTablaActualACSV() {
    // === SELECTOR DE ARCHIVO ===
    JFileChooser selector = new JFileChooser();
    selector.setDialogTitle("Guardar lista de compras como Excel/CSV");

    // Nombre sugerido bonito
    String fechaHora = new SimpleDateFormat("dd-MM-yyyy_HHmm").format(new java.util.Date());
    String nombreSugerido = "Lista_Compras_" + fechaHora + ".csv";
    selector.setSelectedFile(new File(nombreSugerido));

    // Solo archivos CSV
    FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo Excel (*.csv)", "csv");
    selector.setFileFilter(filtro);

    int opcion = selector.showSaveDialog(this);
    if (opcion != JFileChooser.APPROVE_OPTION) {
        return; // Canceló
    }

    File archivo = selector.getSelectedFile();

    // Asegurar extensión .csv
    if (!archivo.getName().toLowerCase().endsWith(".csv")) {
        archivo = new File(archivo.getAbsolutePath() + ".csv");
    }

    // Confirmar sobrescritura
    if (archivo.exists()) {
        int confirmar = JOptionPane.showConfirmDialog(this,
            "El archivo ya existe.\n¿Deseas reemplazarlo?", 
            "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar != JOptionPane.YES_OPTION) {
            return;
        }
    }

    // === EXPORTAR LA TABLA ACTUAL (con filtros aplicados) ===
    try (PrintWriter pw = new PrintWriter(archivo, "UTF-8")) {

        // ENCABEZADOS (sin la columna ID oculta)
        for (int col = 1; col < tblCompras.getColumnCount(); col++) {
            pw.print(tblCompras.getColumnName(col));
            if (col < tblCompras.getColumnCount() - 1) pw.print(",");
        }
        pw.println();

        // FILAS VISIBLES EN LA TABLA
        for (int row = 0; row < tblCompras.getRowCount(); row++) {
            for (int col = 1; col < tblCompras.getColumnCount(); col++) { // Salta columna 0 (ID)
                Object valor = tblCompras.getValueAt(row, col);
                String texto = (valor != null) ? valor.toString() : "";
                // Si contiene comas o comillas, encerrar en comillas dobles
                if (texto.contains(",") || texto.contains("\"") || texto.contains("\n")) {
                    texto = "\"" + texto.replace("\"", "\"\"") + "\"";
                }
                pw.print(texto);
                if (col < tblCompras.getColumnCount() - 1) pw.print(",");
            }
            pw.println();
        }

        JOptionPane.showMessageDialog(this,
            "¡Lista exportada correctamente!\n" + archivo.getAbsolutePath(),
            "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // ABRIR AUTOMÁTICAMENTE CON EXCEL
        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().open(archivo);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error al guardar el archivo:\n" + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}











}