
package Interfaces_Almacenero;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import Conexion.Conexion; // Suponiendo esta ruta
import Entidades.ITProducto; // Suponiendo esta ruta
import Entidades.Sesion; // Suponiendo esta ruta

///PDF
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
/////
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;


import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
/**
 *
 * @author jheff
 */
public class RealizarCompras extends javax.swing.JInternalFrame {
    private static RealizarCompras instancia;
    private int socioIdEncontrado = 0; // Almacena el ID del socio validado
    
    private int idCompraAEditar = 0;
    private String guiaAEditar = "";
    /**
     * Creates new form RealizarCompras
     */
    private RealizarCompras() {
        initComponents();
        this.setBorder(null);
        LblEnlacePrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Cursor de mano
        
        // Eliminar el borde y la barra de título si se desea
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null); 
        this.setBorder(null);
        
        // Cargar los productos al iniciar el formulario
        cargarProductos();
        cargarTablaCompras();
        
        
        
        TxtDniSocio.getDocument().addDocumentListener(new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent e) {
        verificarLongitudYBuscar();
    }
    @Override
    public void removeUpdate(DocumentEvent e) {
        verificarLongitudYBuscar();
    }
    @Override
    public void changedUpdate(DocumentEvent e) { /* Ignorar */ }
});
        
        
        
        
        // 1. LISTENER PARA CALCULAR PRECIO TOTAL
        // Se activa con cada cambio en el campo TxtCantidad.
        TxtCantidad.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) { calcularPrecioTotal(); }
            @Override
            public void removeUpdate(DocumentEvent e) { calcularPrecioTotal(); }
            @Override
            public void insertUpdate(DocumentEvent e) { calcularPrecioTotal(); }
        });

        // 2. LISTENER PARA CALCULAR PRECIO TOTAL
        // Se activa con cada cambio en el campo TxtPrecioCompra (Precio Final).
        TxtPrecioCompra.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) { calcularPrecioTotal(); }
            @Override
            public void removeUpdate(DocumentEvent e) { calcularPrecioTotal(); }
            @Override
            public void insertUpdate(DocumentEvent e) { calcularPrecioTotal(); }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public static RealizarCompras getInstancia() {
        // Verifica si la instancia es nula O si la ventana fue cerrada por el usuario
        if (instancia == null || instancia.isClosed()) {
            instancia = new RealizarCompras();
        }
        return instancia;
    }
    
    
    /**
 * Verifica la longitud del texto y dispara la búsqueda.
 */

/**
 * Verifica la longitud del texto y dispara la búsqueda.
 * Maneja automáticamente DNI (8) y RUC (11).
 */
private void verificarLongitudYBuscar() {
    String dni = TxtDniSocio.getText().trim();
    int longitud = dni.length();
    
    // 1. Longitudes válidas (DNI=8, RUC=11)
    final int LONGITUD_DNI = 8;
    final int LONGITUD_RUC = 11;
    
    // Verificar si la longitud actual es un documento válido
    if (longitud == LONGITUD_DNI || longitud == LONGITUD_RUC) { 
        // Si el largo es 8 o 11, buscamos
        buscarSocioPorDNI(dni); 
        
    } else if (longitud == 0) {
        // 2. Campo vacío: limpiar labels
        LblNombreSocio.setText("Nombre: ");
        socioIdEncontrado = 0;
        
    } else {
        // 3. Longitud inválida (ej. 9, 10, o más de 11): limpiar y mostrar mensaje de espera
        LblNombreSocio.setText("Nombre: (Documento inválido)");
        socioIdEncontrado = 0;
    }
}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LblNombreSocio = new javax.swing.JLabel();
        CbxProducto = new javax.swing.JComboBox<>();
        TxtRendimiento = new javax.swing.JTextField();
        TxtHumedad = new javax.swing.JTextField();
        TxtCantidad = new javax.swing.JTextField();
        TxtPrecioCompra = new javax.swing.JTextField();
        TxtDniSocio = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();
        PdfPTable = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        LblEnlacePrecio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LblPrecioTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCompras = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Producto");

        jLabel2.setText("Rendimiento");

        jLabel3.setText("Humedad");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Precio");

        jLabel6.setText("Dni Socio");

        jLabel7.setText("Nombre");

        LblNombreSocio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TxtHumedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHumedadActionPerformed(evt);
            }
        });

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        PdfPTable.setText("PDF");

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        LblEnlacePrecio.setText("Consultar volsa de valores del cafe");
        LblEnlacePrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblEnlacePrecioMouseClicked(evt);
            }
        });

        jLabel8.setText("Total");

        LblPrecioTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblEnlacePrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(26, 26, 26)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CbxProducto, 0, 80, Short.MAX_VALUE)
                                .addComponent(TxtHumedad)
                                .addComponent(TxtPrecioCompra))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtRendimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(TxtCantidad)
                                .addComponent(LblPrecioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PdfPTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblNombreSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtDniSocio)))))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(CbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtHumedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblPrecioTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TxtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtDniSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(LblNombreSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addComponent(BtnRegistrar)
                .addGap(185, 185, 185)
                .addComponent(PdfPTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnEliminar)
                .addGap(91, 91, 91)
                .addComponent(LblEnlacePrecio)
                .addGap(15, 15, 15))
        );

        TblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblCompras);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtHumedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHumedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHumedadActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
eliminarCompra();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void LblEnlacePrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblEnlacePrecioMouseClicked
    String urlString = "https://es.investing.com/commodities/us-coffee-c";
    try {
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            URI uri = new URI(urlString);
            Desktop.getDesktop().browse(uri);
        } else {
            // Si el sistema no soporta la acción de navegar
            JOptionPane.showMessageDialog(this, 
                "El navegador web no pudo ser abierto. Por favor, copie:\n" + urlString,
                "Error de Navegador", JOptionPane.WARNING_MESSAGE);
        }
    } catch (URISyntaxException | IOException e) {
        JOptionPane.showMessageDialog(this, 
            "Error al abrir el enlace. Verifique la URL.", "Error", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_LblEnlacePrecioMouseClicked

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
if (BtnRegistrar.getText().equals("GUARDAR CAMBIOS")) {
        actualizarCompra();
    } else {
        registrarNuevaCompra();
    }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblComprasMouseClicked
      
    }//GEN-LAST:event_TblComprasMouseClicked

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
iniciarProcesoModificacion();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarActionPerformed

    
    private void cargarProductos() {
        Connection cn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        // Usamos DefaultComboBoxModel para manejar objetos ItemProducto
        DefaultComboBoxModel<ITProducto> modelo = new DefaultComboBoxModel<>();
       

        try {
            cn = Conexion.getConexion();
            String sql = "SELECT id, nombre FROM producto WHERE estado = 'activo' ORDER BY nombre ASC";
            pst = cn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String nombre = rs.getString("nombre");
                modelo.addElement(new ITProducto(id, nombre));
            }
            
            CbxProducto.setModel(modelo); // Asignar el modelo cargado al componente

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cierre de recursos (cn, pst, rs)
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (cn != null) cn.close(); 
            } catch (SQLException ex) {
                 // Manejo de error al cerrar
            }
        }
    }
    
private void buscarSocioPorDNI(String dni) {
    
    Connection cn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        cn = Conexion.getConexion();
        
        // La consulta SQL es la misma
        String sql = "SELECT id, CONCAT(nombre) AS nombre_completo FROM socio WHERE nro_documento = ? LIMIT 1";
        
        pst = cn.prepareStatement(sql);
        pst.setString(1, dni);
        rs = pst.executeQuery();

        if (rs.next()) {
            // Socio Encontrado
            socioIdEncontrado = rs.getInt("id");
            String nombreSocio = rs.getString("nombre_completo");
            LblNombreSocio.setText(nombreSocio);
            
        } else {
            // Socio NO Encontrado
            LblNombreSocio.setText("NO ENCONTRADO - " + dni + ")");
            socioIdEncontrado = 0;
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al buscar el socio: " + e.getMessage());
        LblNombreSocio.setText("Nombre: (ERROR SQL)");
        socioIdEncontrado = 0;
    } finally {
        // 🚨 Cierre de recursos completo y seguro
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (cn != null) cn.close(); 
        } catch (SQLException ex) {
            System.err.println("Error al cerrar recursos en buscarSocioPorDNI: " + ex.getMessage());
        }
    }
}
    
 private String generarGuiaIngreso(Connection cn, int idSocio) throws SQLException {
    
    String iniciales = obtenerInicialesSocio(cn, idSocio); // Llamada al nuevo método
    
    // Obtener fecha (formato DíaMesAño, ej: 121225)
    SimpleDateFormat sdf = new SimpleDateFormat("ddMMyy");
    String fechaGuia = sdf.format(new Date()); 

    // El nuevo prefijo incluye Iniciales y Fecha (ej: JP-121225)
    String prefijoGuia = iniciales + "-" + fechaGuia; 
    
    // ... (El resto del método permanece igual, pero cambia el SQL)
    
    PreparedStatement pst = null;
    ResultSet rs = null;
    String guiaExistente = null;
    int correlativo = 1;

    try {
        // La consulta SQL busca la última guía que empieza con el nuevo prefijo
        String sql = "SELECT guia_ingreso FROM compra WHERE guia_ingreso LIKE CONCAT(?, '-%') ORDER BY id DESC LIMIT 1";
        
        pst = cn.prepareStatement(sql);
        // Usamos el prefijo (ej: JP-121225) como base de búsqueda
        pst.setString(1, prefijoGuia); 
        rs = pst.executeQuery();

        if (rs.next()) {
            guiaExistente = rs.getString("guia_ingreso");
            // Extraer el correlativo (los últimos 3 o 4 caracteres después del guion final)
            // Asumo que la guía es: JP-121225-001
            int ultimoGuion = guiaExistente.lastIndexOf('-');
            String numStr = guiaExistente.substring(ultimoGuion + 1);
            correlativo = Integer.parseInt(numStr) + 1;
        }

    } finally {
        if (rs != null) rs.close();
        if (pst != null) pst.close();
    }
    
    // Formatear el correlativo (ej: 1 -> 001)
    String correlativoStr = String.format("%03d", correlativo); // Formato 001, 002...

    // Resultado final: JP-121225-001
    return prefijoGuia + "-" + correlativoStr;
}   
   
    private void limpiarCamposCompra() {
        TxtDniSocio.setText("");
        TxtCantidad.setText("");
        TxtRendimiento.setText("");
        TxtHumedad.setText("");
        TxtPrecioCompra.setText("");
        
        LblNombreSocio.setText("Nombre: (No Validado)");
        socioIdEncontrado = 0; 
        
        // Reiniciar el ComboBox a la primera opción ("--- Seleccione Producto ---")
        CbxProducto.setSelectedIndex(0); 
    }
    
 public void registrarNuevaCompra() {
    
    // 1. OBTENER Y VALIDAR DATOS (Recuperamos solo Strings por ahora)
    int idUsuario = Sesion.userId;  
    int idSocio = this.socioIdEncontrado;  
    
    // Asegúrese de que este es el nombre de su clase (ItemProducto o ITProducto)
    ITProducto itemProd = (ITProducto) CbxProducto.getSelectedItem();
    
    String precioTotalStr = LblPrecioTotal.getText().trim();

    // Validación de campos clave
    if (itemProd == null || itemProd.getId() == 0 || idSocio == 0) {  
        JOptionPane.showMessageDialog(null, "Debe seleccionar un producto y validar el Socio.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    int idProducto = itemProd.getId();
    
    String cantidadStr = TxtCantidad.getText().trim();
    String rendimientoStr = TxtRendimiento.getText().trim();
    String humedadStr = TxtHumedad.getText().trim();
    String precioStr = TxtPrecioCompra.getText().trim();  
    // Eliminada: int cantidad = TxtCantidad.getText(int).trim() <<< LÍNEA INCORRECTA

    if (cantidadStr.isEmpty() || rendimientoStr.isEmpty() || humedadStr.isEmpty() || precioStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe completar todos los campos de compra.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        return;
    }
    precioTotalStr = precioTotalStr.replace(",", "");
    Connection cn = null;
    PreparedStatement pst = null;

    try {
        // *****************************************************************
        // ** CONVERSIÓN DE STRING A DOUBLE (DEBE ESTAR DENTRO DEL TRY) **
        // *****************************************************************
        double cantidad = Double.parseDouble(cantidadStr);
        double rendimiento = Double.parseDouble(rendimientoStr);
        double humedad = Double.parseDouble(humedadStr);
        double precioFinal = Double.parseDouble(precioStr);
        
        if (rendimiento < 0 || rendimiento > 100 || humedad < 0 || humedad > 20) {
            JOptionPane.showMessageDialog(null, "Rendimiento (0-100) y Humedad (0-20) fuera de rango.", "Error de Rango", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double precioTotal = Double.parseDouble(precioTotalStr);
        cn = Conexion.getConexion();
        
        String guiaIngresoGenerada = generarGuiaIngreso(cn , idSocio);
        
        // 3. EJECUTAR EL INSERT (Incluyendo la 'unidad')
        String sql = "INSERT INTO compra (id_usuario, id_producto, unidad, id_socio, rendimiento, humedad, guia_ingreso, cantidad, precio,precio_total) " +
                     "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?,?)"; 

        pst = cn.prepareStatement(sql);
        pst.setInt(1, idUsuario);
        pst.setInt(2, idProducto);
        pst.setString(3, "Quintales"); 

        pst.setInt(4, idSocio);
        // *****************************************************************
        // ** USO DE LAS VARIABLES DOUBLE CONVERTIDAS (CORRECCIÓN CRÍTICA) **
        // *****************************************************************
        pst.setDouble(5, rendimiento); // Antes usaba rendimientoStr (String)
        pst.setDouble(6, humedad);    // Antes usaba humedadStr (String)
        pst.setString(7, guiaIngresoGenerada); 
        pst.setDouble(8, cantidad);   // Antes usaba setDouble(8, cantidad) - Correcto
        pst.setDouble(9, precioFinal); 
        pst.setDouble(10, precioTotal);
        
        pst.executeUpdate();
            
       
        JOptionPane.showMessageDialog(null, "¡Compra registrada! Guía N°: " + guiaIngresoGenerada, "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCamposCompra(); 
        cargarTablaCompras();

   
        } catch (SQLException e) {
         
        e.printStackTrace(); 
        JOptionPane.showMessageDialog(null, "Error al registrar la compra. Causa: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Cierre de recursos
        try {
            if (pst != null) pst.close();
            if (cn != null) cn.close(); 
        } catch (SQLException ex) {
            System.err.println("Error al cerrar recursos: " + ex.getMessage());
        }
    }
}
 
private String obtenerInicialesSocio(Connection cn, int idSocio) throws SQLException {
    PreparedStatement pst = null;
    ResultSet rs = null;
    String iniciales = "";

    try {
        // Obtenemos el nombre y apellido (asumo que se concatenan en la tabla)
        String sql = "SELECT CONCAT(nombre) AS nombre_completo FROM socio WHERE id = ?";
        pst = cn.prepareStatement(sql);
        pst.setInt(1, idSocio);
        rs = pst.executeQuery();

        if (rs.next()) {
            String nombreCompleto = rs.getString("nombre_completo").trim();
            if (nombreCompleto.isEmpty()) {
                return "XX"; // Valor por defecto si el nombre está vacío
            }

            // Lógica para tomar la primera letra de cada palabra
            String[] partes = nombreCompleto.toUpperCase().split("\\s+");
            for (String parte : partes) {
                if (!parte.isEmpty()) {
                    iniciales += parte.charAt(0);
                }
            }
        } else {
            return "??"; // Socio no encontrado
        }

    } finally {
        if (rs != null) rs.close();
        if (pst != null) pst.close();
        // NOTA: NO CERRAR 'cn'
    }
    return iniciales.length() > 2 ? iniciales.substring(0, 2) : iniciales; // Limitar a 2 iniciales (ej. JP)
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<Entidades.ITProducto> CbxProducto;
    private javax.swing.JLabel LblEnlacePrecio;
    private javax.swing.JLabel LblNombreSocio;
    private javax.swing.JLabel LblPrecioTotal;
    private javax.swing.JButton PdfPTable;
    private javax.swing.JTable TblCompras;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtDniSocio;
    private javax.swing.JTextField TxtHumedad;
    private javax.swing.JTextField TxtPrecioCompra;
    private javax.swing.JTextField TxtRendimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

public void cargarTablaCompras() {
    
    String[] titulos = {"ID", "Guía", "Fecha", "Socio", "Producto", "Cantidad","Rendimiento","Humedad", "Precio base","Total"};
DefaultTableModel modelo = new DefaultTableModel(null, titulos) {
    @Override
    public boolean isCellEditable(int row, int column) { return false; }
    @Override
    public Class<?> getColumnClass(int columnIndex) {
        return columnIndex == 0 ? Integer.class : super.getColumnClass(columnIndex);
    }
};

    TblCompras.setModel(modelo); // Asigna el modelo a la tabla
    
    Connection cn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        cn = Conexion.getConexion();
        
        // Consulta SQL para obtener las últimas compras con nombres
        // NOTA: Cambie 's.nombre' si su tabla usa 's.nombres' o 's.apellidos'
        
String sql = "SELECT " +
                     "c.id, c.guia_ingreso, c.fecha_registro, " +
                     "s.nombre AS nombre_socio, " +
                     "p.nombre AS nombre_producto, " +
                     "c.cantidad, c.rendimiento, c.humedad, c.precio, c.precio_total " +
                     "FROM compra c " +
                     "JOIN socio s ON c.id_socio = s.id " +
                     "JOIN producto p ON c.id_producto = p.id " +
                     "ORDER BY c.id DESC LIMIT 15";

        pst = cn.prepareStatement(sql);
        rs = pst.executeQuery();

        // 3. Iterar sobre los resultados y añadir filas al modelo
        
// Luego en el while, cambia el orden:
        while (rs.next()) {
            Object[] fila = new Object[10];
            fila[0] = rs.getInt("c.id");                    // ← ID oculto
            fila[1] = rs.getString("guia_ingreso");
            fila[2] = rs.getTimestamp("fecha_registro");
            fila[3] = rs.getString("nombre_socio");
            fila[4] = rs.getString("nombre_producto");
            fila[5] = rs.getDouble("cantidad");
            fila[6] = rs.getDouble("rendimiento");
            fila[7] = rs.getDouble("humedad");
            fila[8] = rs.getDouble("precio");
            fila[9] = rs.getDouble("precio_total");
            modelo.addRow(fila);
        }
        TblCompras.getColumnModel().getColumn(0).setPreferredWidth(0);
        TblCompras.getColumnModel().getColumn(0).setMinWidth(0);
        TblCompras.getColumnModel().getColumn(0).setMaxWidth(0);
       
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar la tabla de compras: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        // Cierre seguro de recursos
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            // Cerrar la conexión aquí si no se usa AutoCommit=false, sino cerrarla en el método que la abre.
            // Si su método Conexion.getConexion() abre una nueva, debe cerrarse aquí:
            if (cn != null) cn.close(); 
        } catch (SQLException ex) {
            // Manejo de error al cerrar
        }
    }
    TblCompras.getSelectionModel().addListSelectionListener(e -> {
    boolean seleccionado = TblCompras.getSelectedRow() != -1;
    BtnModificar.setEnabled(seleccionado);
    BtnEliminar.setEnabled(seleccionado);
});
    
}

private void calcularPrecioTotal() {
    try {
        String cantidadStr = TxtCantidad.getText().trim();
        String precioFinalStr = TxtPrecioCompra.getText().trim();
        
        // Si algún campo está vacío, mostramos 0.00 y terminamos
        if (cantidadStr.isEmpty() || precioFinalStr.isEmpty()) {
            LblPrecioTotal.setText("0.00");
            return;
        }

        // Conversión y cálculo
        double cantidad = Double.parseDouble(cantidadStr);
        double precioFinal = Double.parseDouble(precioFinalStr);
        
        double precioTotal = cantidad * precioFinal;
        
        // Formatear a dos decimales y asignar al JLabel
        // Se usa String.format() para asegurar el formato de moneda.
        LblPrecioTotal.setText(String.format("%,.2f", precioTotal)); 

    } catch (NumberFormatException e) {
        // Si hay un error de formato (ej. el usuario escribe letras), mostrar error o 0.00
        LblPrecioTotal.setText("Error en datos");
    }
}

private void habilitarModoEdicion() {
    BtnRegistrar.setText("GUARDAR CAMBIOS");
    BtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // opcional
    
    // Deshabilitar campos que no se deben modificar
    TxtDniSocio.setEnabled(false);
    CbxProducto.setEnabled(true);
    TxtCantidad.setEnabled(true);
    TxtRendimiento.setEnabled(true);
    TxtHumedad.setEnabled(true);
    TxtPrecioCompra.setEnabled(true);
    
    BtnModificar.setEnabled(false);
}

private void deshabilitarModoEdicion() {
    BtnRegistrar.setText("REGISTRAR COMPRA");
    BtnRegistrar.setActionCommand("REGISTRAR");
    
    // ** NUEVO: HABILITAR el botón Modificar **
    BtnModificar.setEnabled(true); 
    
    TxtDniSocio.setEnabled(true);
    LblNombreSocio.setEnabled(false);// Habilitar búsqueda de socio
    // ... (limpieza y reinicio de variables) ...
}

private void cargarDetallesCompraPorId(int idCompra) {
    Connection cn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    try {
        cn = Conexion.getConexion();
       
        String sql = "SELECT id, id_socio, id_producto, cantidad, rendimiento, humedad, precio, precio_total "
                   + "FROM compra WHERE id = ?";
       
        pst = cn.prepareStatement(sql);
        pst.setInt(1, idCompra);
        rs = pst.executeQuery();
        
        if (rs.next()) {
            this.idCompraAEditar = rs.getInt("id");
            int idSocio = rs.getInt("id_socio");
            int idProducto = rs.getInt("id_producto");
            
            double cantidad = rs.getDouble("cantidad");
            double rendimiento = rs.getDouble("rendimiento");
            double humedad = rs.getDouble("humedad");
            double precio = rs.getDouble("precio");

            // CARGAR SOCIO Y PRODUCTO USANDO LA MISMA CONEXIÓN
            cargarSocioParaEdicion(idSocio, cn);      // ← pasa cn
            seleccionarProductoPorId(idProducto, cn); // ← pasa cn

            // Llenar campos
            TxtCantidad.setText(String.valueOf(cantidad));
            TxtRendimiento.setText(String.valueOf(rendimiento));
            TxtHumedad.setText(String.valueOf(humedad));
            TxtPrecioCompra.setText(String.valueOf(precio));
            
            calcularPrecioTotal();
            habilitarModoEdicion(); // ← cambia el botón a "GUARDAR CAMBIOS"
        }
       
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar compra: " + e.getMessage());
        e.printStackTrace();
    } finally {
        // CIERRA TODO AQUÍ
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (cn != null) cn.close();  // ← CIERRE DE CONEXIÓN
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}

private void iniciarProcesoModificacion() {
    int fila = TblCompras.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una compra para modificar");
        return;
    }
    
    int idCompra = (int) TblCompras.getValueAt(fila, 0);
    cargarDetallesCompraPorId(idCompra);
}

/**
 * Busca y selecciona el producto en el ComboBox usando su ID.
 * @param idProducto El ID del producto a seleccionar.
 */
private void seleccionarProductoPorId(int idProducto, Connection cn) {
    PreparedStatement pst = null;
    ResultSet rs = null;
    try {
        String sql = "SELECT id, nombre FROM producto WHERE id = ?";
        pst = cn.prepareStatement(sql);
        pst.setInt(1, idProducto);
        rs = pst.executeQuery();
        
        if (rs.next()) {
            DefaultComboBoxModel<ITProducto> model = (DefaultComboBoxModel<ITProducto>) CbxProducto.getModel();
            for (int i = 0; i < model.getSize(); i++) {
                ITProducto item = model.getElementAt(i);
                if (item.getId() == idProducto) {
                    CbxProducto.setSelectedItem(item);
                    break;
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            // NO CIERRES cn
        } catch (SQLException ex) { ex.printStackTrace(); }
    }
}

private void cargarSocioParaEdicion(int idSocio, Connection cn) {
    PreparedStatement pst = null;
    ResultSet rs = null;
    try {
        String sql = "SELECT nro_documento, nombre FROM socio WHERE id = ?";
        pst = cn.prepareStatement(sql);
        pst.setInt(1, idSocio);
        rs = pst.executeQuery();
        
        if (rs.next()) {
            TxtDniSocio.setText(rs.getString("nro_documento"));
            LblNombreSocio.setText(rs.getString("nombre"));
            this.socioIdEncontrado = idSocio;
            TxtDniSocio.setEnabled(false);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            // NO CIERRES cn AQUÍ
        } catch (SQLException ex) { ex.printStackTrace(); }
    }
}

private void actualizarCompra() {
    if (idCompraAEditar == 0) {
        JOptionPane.showMessageDialog(this, "No hay compra seleccionada para editar");
        return;
    }

    Connection cn = null;
    PreparedStatement pst = null;

    try {
        cn = Conexion.getConexion();

        ITProducto prod = (ITProducto) CbxProducto.getSelectedItem();
        double cantidad = Double.parseDouble(TxtCantidad.getText());
        double rendimiento = Double.parseDouble(TxtRendimiento.getText());
        double humedad = Double.parseDouble(TxtHumedad.getText());
        double precio = Double.parseDouble(TxtPrecioCompra.getText());
        double total = cantidad * precio;

        String sql = "UPDATE compra SET id_producto=?, cantidad=?, rendimiento=?, humedad=?, precio=?, precio_total=? WHERE id=?";
        pst = cn.prepareStatement(sql);
        pst.setInt(1, prod.getId());
        pst.setDouble(2, cantidad);
        pst.setDouble(3, rendimiento);
        pst.setDouble(4, humedad);
        pst.setDouble(5, precio);
        pst.setDouble(6, total);
        pst.setInt(7, idCompraAEditar);

        int filas = pst.executeUpdate();
        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "¡Compra actualizada correctamente!");
            cargarTablaCompras();
            limpiarCamposCompra();
            BtnRegistrar.setText("REGISTRAR COMPRA");
            BtnModificar.setEnabled(true);
            TxtDniSocio.setEnabled(true);
            idCompraAEditar = 0;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try {
            if (pst != null) pst.close();
            if (cn != null) cn.close();
        } catch (SQLException ex) { ex.printStackTrace(); }
    }
}

private void registrarEnBitacora(String tabla, String accion, String descripcion) {
    try (Connection cn = Conexion.getConexion();
         PreparedStatement pst = cn.prepareStatement(
             "INSERT INTO bitacora (tabla_afectada, accion, descripcion, id_usuario) VALUES (?, ?, ?, ?)")) {
        
        pst.setString(1, tabla);
        pst.setString(2, accion);
        pst.setString(3, descripcion);
        pst.setInt(4, Sesion.userId);
        pst.executeUpdate();
        
    } catch (SQLException e) {
        System.err.println("Error bitácora: " + e.getMessage());
    }
}



///////////////////////////////////////ELIMINAR/////////////////////////////////////////////
///
private void eliminarCompra() {
    int fila = TblCompras.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una compra para eliminar", 
                                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int idCompra = (int) TblCompras.getValueAt(fila, 0);
    String guia = TblCompras.getValueAt(fila, 1).toString();

    // Confirmación doble
    int opcion = JOptionPane.showConfirmDialog(this,
        "<html><b>¿Eliminar permanentemente esta compra?</b><br>" +
        "Guía: <b>" + guia + "</b><br>" +
        "Esta acción NO se puede deshacer.</html>",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);

    if (opcion != JOptionPane.YES_OPTION) {
        return;
    }

    // === ELIMINAR CON CONEXIÓN NUEVA Y FRESCA ===
    Connection cn = null;
    PreparedStatement pst = null;

    try {
        // ¡SIEMPRE abre una conexión NUEVA aquí!
        cn = Conexion.getConexion();  // ← conexión fresca
        cn.setAutoCommit(false);

        String sql = "DELETE FROM compra WHERE id = ?";
        pst = cn.prepareStatement(sql);
        pst.setInt(1, idCompra);

        int filas = pst.executeUpdate();

        if (filas > 0) {
            // Bitácora
            registrarEnBitacora("compra", "DELETE", 
                "Eliminada compra ID=" + idCompra + ", Guía=" + guia + 
                ", Usuario=" + Sesion.usuarioActual);

            cn.commit();

            JOptionPane.showMessageDialog(this, 
                "¡Compra eliminada correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            cargarTablaCompras(); // recarga la tabla
        }

    } catch (SQLException e) {
        try { if (cn != null) cn.rollback(); } catch (Exception ex) {}
        JOptionPane.showMessageDialog(this, 
            "Error al eliminar:\n" + e.getMessage(), 
            "Error SQL", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        // CIERRE SEGURO (nunca falla)
        try { if (pst != null) pst.close(); } catch (Exception e) {}
        try { if (cn != null) { cn.setAutoCommit(true); cn.close(); } } catch (Exception e) {}
    }
}

///////////////////////////PDF////////////////////////////////////
private void generarGuiaPDF() {
    int fila = TblCompras.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una compra para generar la guía", 
                                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        String guia = TblCompras.getValueAt(fila, 1).toString();
        String fecha = new SimpleDateFormat("dd/MM/yyyy HH:mm")
                      .format(TblCompras.getValueAt(fila, 2));
        String socio = TblCompras.getValueAt(fila, 3).toString();
        String producto = TblCompras.getValueAt(fila, 4).toString();
        double cantidad = (double) TblCompras.getValueAt(fila, 5);
        String rendimiento = TblCompras.getValueAt(fila, 6).toString();
        String humedad = TblCompras.getValueAt(fila, 7).toString();
        double precio = (double) TblCompras.getValueAt(fila, 8);
        double total = (double) TblCompras.getValueAt(fila, 9);

        String ruta = System.getProperty("user.home") + "/Desktop/GUIA_" + guia + ".pdf";

        Document documento = new Document(PageSize.A4, 50, 50, 50, 50);
        PdfWriter.getInstance(documento, new FileOutputStream(ruta));
        documento.open();

        Font titulo = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Font normal = FontFactory.getFont(FontFactory.HELVETICA, 12);
        Font negrita = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
        Font grande = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);

        // Encabezado centrado
        Paragraph p = new Paragraph("COOPERATIVA AGRARIA CAFÉ BAQUA GRANDE", titulo);
        p.setAlignment(Element.ALIGN_CENTER);
        documento.add(p);

        p = new Paragraph("GUÍA DE INGRESO - Nº " + guia, grande);
        p.setAlignment(Element.ALIGN_CENTER);
        p.setSpacingBefore(10);
        documento.add(p);

        p = new Paragraph("Fecha: " + fecha, normal);
        p.setAlignment(Element.ALIGN_CENTER);
        documento.add(p);

        documento.add(new Paragraph("\n"));

        // Tabla
        PdfPTable tabla = new PdfPTable(2);
        tabla.setWidthPercentage(90);
        tabla.setWidths(new int[]{35, 65});

        tabla.addCell(new PdfPCell(new Phrase("Socio:", negrita)));
        tabla.addCell(new PdfPCell(new Phrase(socio, normal)));
        tabla.addCell(new PdfPCell(new Phrase("Producto:", negrita)));
        tabla.addCell(new PdfPCell(new Phrase(producto, normal)));
        tabla.addCell(new PdfPCell(new Phrase("Cantidad:", negrita)));
        tabla.addCell(new PdfPCell(new Phrase(cantidad + " qq", normal)));
        tabla.addCell(new PdfPCell(new Phrase("Rendimiento:", negrita)));
        tabla.addCell(new PdfPCell(new Phrase(rendimiento + " %", normal)));
        tabla.addCell(new PdfPCell(new Phrase("Humedad:", negrita)));
        tabla.addCell(new PdfPCell(new Phrase(humedad + " %", normal)));
        tabla.addCell(new PdfPCell(new Phrase("Precio por qq:", negrita)));
        tabla.addCell(new PdfPCell(new Phrase("S/ " + String.format("%.2f", precio), normal)));
        tabla.addCell(new PdfPCell(new Phrase("TOTAL A PAGAR:", negrita)));
        PdfPCell celdaTotal = new PdfPCell(new Phrase("S/ " + String.format("%.2f", total), 
                                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16)));
        celdaTotal.setHorizontalAlignment(Element.ALIGN_RIGHT);
        celdaTotal.setColspan(1);
        tabla.addCell(celdaTotal);

        documento.add(tabla);

        // Firmas
        documento.add(new Paragraph("\n\n\n"));
        p = new Paragraph("_________________           _________________", normal);
        p.setAlignment(Element.ALIGN_CENTER);
        documento.add(p);
        p = new Paragraph("    FIRMA SOCIO                       FIRMA ALMACENERO", normal);
        p.setAlignment(Element.ALIGN_CENTER);
        documento.add(p);

        documento.close();

        JOptionPane.showMessageDialog(this, 
            "¡GUÍA GENERADA CORRECTAMENTE!\nGuardada en el Escritorio", 
            "ÉXITO", JOptionPane.INFORMATION_MESSAGE);

        // ABRIR AUTOMÁTICAMENTE
        Desktop.getDesktop().open(new File(ruta));

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al generar PDF:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

}



